### ISSUE TITLE
Broken HelloWorld with 1.3

### ISSUE THREAD

**Issue by romant** [joeeames/AngularFundamentalsFiles#11]
Since globals aren't in by default a suggested modification might be to include:
#### head / body
```
ng-app="app"
```
#### and for the controller
```
angular.module("app", [])
    .controller("HelloWorldCtrl", function($scope) {
        $scope.helloMessage = "lorem foo";
    } );
```

**Comment by joeeames** [comment]
thank you.  Yes we are in the middle of an update to this course. I had considered just taking the clip out, but this is a great suggestion. Thank you again.

**Comment by smacky311** [comment]
Haha.  Now I see this bug already listed here :).  Here's what you have to do to fix hello world:  http://stackoverflow.com/questions/28678987/has-angular-changed-recently-to-require-adding-modules-and-controllers-via-funct/28679079#28679079

**Comment by joeeames** [comment]
fixed with update to course
