### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by tbrentlong** [joeeames/AngularFundamentalsFiles#14]
I'm following the videos and have installed git for windows/bash/etc and downloaded the copy of the angular-seed-master zip from this site.  When I type 'npm start', I get the following

$ npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Brent\angular-seed-master\app\npm-debug.log

**Comment by samrosedotme** [comment]
I am having the same error on a Mac.

**Comment by joeeames** [comment]
this is being addressed in the course update. we are completely removing angular seed from the course as it is extremely out of date.
