### ISSUE TITLE
Revisit the Testing Modules and fix issues

### ISSUE THREAD

**Issue by jderus** [joeeames/AngularFundamentalsFiles#16]
There appears to be some old and out of sync content in the testing modules.
You should consider revisiting these modules to ensure that what you are presenting, is what someone would actually have|see. If you do not want to re-record, please consider adding notes to the video for updates.

Some examples are trivial:
*incorrectly named dirs - "partials" vs "templates"

Some examples are not so trivial
*missing e2e-test.bat 
*e2e-test.bat from seed doesnt match the project structure from DemoApp
(overall cleaning up the situation so that the seed is actually a seed for the DemoApp would help here)

**Comment by joeeames** [comment]
course has been updated. :) cheers
