### ISSUE TITLE
Not getting the expected output when running protractor tests

### ISSUE THREAD

**Issue by benajo** [joeeames/AngularFundamentalsFiles#19]
Following the tutorial exactly the output doesn't have `x test, x assertion, x failures` as expected it has the format `x specs, x failures`.

```
$ protractor test/protractor.conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
WARNING - more than one element found for locator by.binding("event.name") - the first result will be used
......


6 specs, 0 failures
Finished in 3.785 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

**Comment by benajo** [comment]
I've discovered that this issue is because of the latest version of protractor, v3.0.0.

I installed v2.5.1 and I get `x test, x assertion, x failures` instead of `x specs, x failures` now.

**Comment by joeeames** [comment]
thanks for pointing this out.
