### ISSUE TITLE
Missing path module

### ISSUE THREAD

**Issue by francofs** [joeeames/AngularFundamentalsFiles#20]
I'm using WebStorm and whilte writing the web-server.js file, it cannot resolve the path module on node. No problem with express module though.

I tried installing path module with npm, but is seems it's not the same used in the course.

**Comment by joeeames** [comment]
@francofs this is a good note, but not sure that there's anything there that can be done about it in relation to this course. I'm going to close the issue unless there's something that needs to be changed in the course.
