### ISSUE TITLE
Missing angular-sanitize.js in EditProfile.html

### ISSUE THREAD

**Issue by blakekolb** [joeeames/AngularFundamentalsFiles#21]
I think you guys are missing the "<script src="/lib/angular/angular-sanitize.js"></script>" line in EditProfile.html in your zip (both in the original and finished folders). 

Without it I wasn't able to use the getGravatarUrl function to change the image when I was working on the PluralSight course "Angular Fundamentals" and I got to the 3rd section of "Creating and using Angular services". It gave me a console error too, so I'm attaching that for your viewing/debugging pleasure.

While I have your attention, thanks so much for this course! I am only half way through but I have learned a huge amount already. Your course is clear and concise while still delivering a great amount of very useful information. I will be taking at least one more course form you guys after this on Angular, and if you have a bootstrap course, I will be taking that too.

![editprofilejserror-pluralsight](https://cloud.githubusercontent.com/assets/17161600/12949973/ca79e550-cfd8-11e5-9132-c2d39c5271d7.png)

**Comment by blakekolb** [comment]
I think I actually had something in my app.js that was still loading ng-sanitize. nevermind! Learning is certainly humbling!

**Comment by joeeames** [comment]
not at all. Glad you figured out. And we'd much rather have people be
willing to point out things that could be problems, than people saying
nothing.

On Wed, Feb 10, 2016 at 11:00 AM, blakekolb <notifications@github.com>
wrote:

> I think I actually had something in my app.js that was still loading
> ng-sanitize. nevermind! Learning is certainly humbling!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeeames/AngularFundamentalsFiles/issues/21#issuecomment-182504867>
> .
>



-- 
Joe Eames
Software Craftsman

**Comment by cramirezFour51** [comment]
Shouldn't the script source for ng-sanitize be included on the editProfile.html? I got the same issue and resolved it by adding that script.
