### ISSUE TITLE
Filtering by Intermediate produces zero results

### ISSUE THREAD

**Issue by bowyer99** [joeeames/AngularFundamentalsFiles#22]
On the EventDetails on the when selecting Intermediate produces no results as the filtering is in the incorrect order on the ng-repeat. 
It limits the collection of items first and then tries to filter by query.level

I fixed it locally by changing:
`<li ng-repeat="session in event.sessions | orderBy:sortorder | limitTo:2 | filter:query">`
to
`<li ng-repeat="session in event.sessions | orderBy:sortorder | filter:query | limitTo:2">`

This then filters the data **and then** takes the top 2 items from the list

**Comment by joeeames** [comment]
Thanks for the catch. We'll put this on the list for the next course update.
