### ISSUE TITLE
DemoApp-Finished Doesn't Function

### ISSUE THREAD

**Issue by davidtaylorjr** [joeeames/AngularFundamentalsFiles#27]
When you unzip the Demo App Finished, run `npm install` and fire up the server it only comes up with a blank page that has a navbar and a link to the Create Event.

I also ran into issues following the video tutorial about 1/3 of the way through when you build out the data service and api, the server breaks and doesn't load any of the material.

**Comment by joeeames** [comment]
run "server.sh" or "server.bat" whichever is appropriate for you.

For your issues following the tutorial, see the discussions on pluralsight.com for this course. It's very common for this to happen by just missing something very small. If you have further issues, post in the discussion forum for the course.

**Comment by davidtaylorjr** [comment]
@joeeames That's what I am saying. When running server.sh or server.bat neither work. The server loads, you see the page but the content does not load.

This is specifically on the "Finished" version which means I didn't miss anything in the code.  Not sure what is going on.
