### ISSUE TITLE
npm install cannot download karma files

### ISSUE THREAD

**Issue by reeveha** [joeeames/AngularFundamentalsFiles#7]
Tried to run the npm install and it errors with the ECONNRESET with trying to download the Karma files.  Here is the log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ 'C:\\Users\\reevesh\\Downloads\\AngularDemos\\angular-seed-master',
6 verbose install   [ 'phantomjs',
6 verbose install     'karma',
6 verbose install     'karma-junit-reporter',
6 verbose install     'karma-jasmine',
6 verbose install     'karma-ng-scenario' ] ]
7 info preinstall angularjs-seed@
8 verbose readDependencies using package.json deps
9 verbose cache add [ 'phantomjs@~1.9', null ]
10 verbose cache add name=undefined spec="phantomjs@~1.9" args=["phantomjs@~1.9",null]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'phantomjs@~1.9',
11 verbose parsed url   path: 'phantomjs@~1.9',
11 verbose parsed url   href: 'phantomjs@~1.9' }
12 verbose cache add [ 'karma@~0.10', null ]
13 verbose cache add name=undefined spec="karma@~0.10" args=["karma@~0.10",null]
14 verbose parsed url { protocol: null,
14 verbose parsed url   slashes: null,
14 verbose parsed url   auth: null,
14 verbose parsed url   host: null,
14 verbose parsed url   port: null,
14 verbose parsed url   hostname: null,
14 verbose parsed url   hash: null,
14 verbose parsed url   search: null,
14 verbose parsed url   query: null,
14 verbose parsed url   pathname: 'karma@~0.10',
14 verbose parsed url   path: 'karma@~0.10',
14 verbose parsed url   href: 'karma@~0.10' }
15 verbose cache add [ 'karma-junit-reporter@~0.1', null ]
16 verbose cache add name=undefined spec="karma-junit-reporter@~0.1" args=["karma-junit-reporter@~0.1",null]
17 verbose parsed url { protocol: null,
17 verbose parsed url   slashes: null,
17 verbose parsed url   auth: null,
17 verbose parsed url   host: null,
17 verbose parsed url   port: null,
17 verbose parsed url   hostname: null,
17 verbose parsed url   hash: null,
17 verbose parsed url   search: null,
17 verbose parsed url   query: null,
17 verbose parsed url   pathname: 'karma-junit-reporter@~0.1',
17 verbose parsed url   path: 'karma-junit-reporter@~0.1',
17 verbose parsed url   href: 'karma-junit-reporter@~0.1' }
18 verbose cache add [ 'karma-jasmine@~0.1', null ]
19 verbose cache add name=undefined spec="karma-jasmine@~0.1" args=["karma-jasmine@~0.1",null]
20 verbose parsed url { protocol: null,
20 verbose parsed url   slashes: null,
20 verbose parsed url   auth: null,
20 verbose parsed url   host: null,
20 verbose parsed url   port: null,
20 verbose parsed url   hostname: null,
20 verbose parsed url   hash: null,
20 verbose parsed url   search: null,
20 verbose parsed url   query: null,
20 verbose parsed url   pathname: 'karma-jasmine@~0.1',
20 verbose parsed url   path: 'karma-jasmine@~0.1',
20 verbose parsed url   href: 'karma-jasmine@~0.1' }
21 verbose cache add [ 'karma-ng-scenario@~0.1', null ]
22 verbose cache add name=undefined spec="karma-ng-scenario@~0.1" args=["karma-ng-scenario@~0.1",null]
23 verbose parsed url { protocol: null,
23 verbose parsed url   slashes: null,
23 verbose parsed url   auth: null,
23 verbose parsed url   host: null,
23 verbose parsed url   port: null,
23 verbose parsed url   hostname: null,
23 verbose parsed url   hash: null,
23 verbose parsed url   search: null,
23 verbose parsed url   query: null,
23 verbose parsed url   pathname: 'karma-ng-scenario@~0.1',
23 verbose parsed url   path: 'karma-ng-scenario@~0.1',
23 verbose parsed url   href: 'karma-ng-scenario@~0.1' }
24 verbose cache add name="phantomjs" spec="~1.9" args=["phantomjs","~1.9"]
25 verbose parsed url { protocol: null,
25 verbose parsed url   slashes: null,
25 verbose parsed url   auth: null,
25 verbose parsed url   host: null,
25 verbose parsed url   port: null,
25 verbose parsed url   hostname: null,
25 verbose parsed url   hash: null,
25 verbose parsed url   search: null,
25 verbose parsed url   query: null,
25 verbose parsed url   pathname: '~1.9',
25 verbose parsed url   path: '~1.9',
25 verbose parsed url   href: '~1.9' }
26 verbose addNamed [ 'phantomjs', '~1.9' ]
27 verbose addNamed [ null, '>=1.9.0-0 <1.10.0-0' ]
28 verbose cache add name="karma" spec="~0.10" args=["karma","~0.10"]
29 verbose parsed url { protocol: null,
29 verbose parsed url   slashes: null,
29 verbose parsed url   auth: null,
29 verbose parsed url   host: null,
29 verbose parsed url   port: null,
29 verbose parsed url   hostname: null,
29 verbose parsed url   hash: null,
29 verbose parsed url   search: null,
29 verbose parsed url   query: null,
29 verbose parsed url   pathname: '~0.10',
29 verbose parsed url   path: '~0.10',
29 verbose parsed url   href: '~0.10' }
30 verbose addNamed [ 'karma', '~0.10' ]
31 verbose addNamed [ null, '>=0.10.0-0 <0.11.0-0' ]
32 verbose cache add name="karma-junit-reporter" spec="~0.1" args=["karma-junit-reporter","~0.1"]
33 verbose parsed url { protocol: null,
33 verbose parsed url   slashes: null,
33 verbose parsed url   auth: null,
33 verbose parsed url   host: null,
33 verbose parsed url   port: null,
33 verbose parsed url   hostname: null,
33 verbose parsed url   hash: null,
33 verbose parsed url   search: null,
33 verbose parsed url   query: null,
33 verbose parsed url   pathname: '~0.1',
33 verbose parsed url   path: '~0.1',
33 verbose parsed url   href: '~0.1' }
34 verbose addNamed [ 'karma-junit-reporter', '~0.1' ]
35 verbose addNamed [ null, '>=0.1.0-0 <0.2.0-0' ]
36 verbose cache add name="karma-jasmine" spec="~0.1" args=["karma-jasmine","~0.1"]
37 verbose parsed url { protocol: null,
37 verbose parsed url   slashes: null,
37 verbose parsed url   auth: null,
37 verbose parsed url   host: null,
37 verbose parsed url   port: null,
37 verbose parsed url   hostname: null,
37 verbose parsed url   hash: null,
37 verbose parsed url   search: null,
37 verbose parsed url   query: null,
37 verbose parsed url   pathname: '~0.1',
37 verbose parsed url   path: '~0.1',
37 verbose parsed url   href: '~0.1' }
38 verbose addNamed [ 'karma-jasmine', '~0.1' ]
39 verbose addNamed [ null, '>=0.1.0-0 <0.2.0-0' ]
40 verbose cache add name="karma-ng-scenario" spec="~0.1" args=["karma-ng-scenario","~0.1"]
41 verbose parsed url { protocol: null,
41 verbose parsed url   slashes: null,
41 verbose parsed url   auth: null,
41 verbose parsed url   host: null,
41 verbose parsed url   port: null,
41 verbose parsed url   hostname: null,
41 verbose parsed url   hash: null,
41 verbose parsed url   search: null,
41 verbose parsed url   query: null,
41 verbose parsed url   pathname: '~0.1',
41 verbose parsed url   path: '~0.1',
41 verbose parsed url   href: '~0.1' }
42 verbose addNamed [ 'karma-ng-scenario', '~0.1' ]
43 verbose addNamed [ null, '>=0.1.0-0 <0.2.0-0' ]
44 silly lockFile 472de541-phantomjs-1-9 phantomjs@~1.9
45 verbose lock phantomjs@~1.9 C:\Users\reevesh\AppData\Roaming\npm-cache\472de541-phantomjs-1-9.lock
46 silly lockFile 059b5650-karma-0-10 karma@~0.10
47 verbose lock karma@~0.10 C:\Users\reevesh\AppData\Roaming\npm-cache\059b5650-karma-0-10.lock
48 silly lockFile dbcabe50-karma-junit-reporter-0-1 karma-junit-reporter@~0.1
49 verbose lock karma-junit-reporter@~0.1 C:\Users\reevesh\AppData\Roaming\npm-cache\dbcabe50-karma-junit-reporter-0-1.lock
50 silly lockFile 0a4b2533-karma-jasmine-0-1 karma-jasmine@~0.1
51 verbose lock karma-jasmine@~0.1 C:\Users\reevesh\AppData\Roaming\npm-cache\0a4b2533-karma-jasmine-0-1.lock
52 silly lockFile 8186ecb3-karma-ng-scenario-0-1 karma-ng-scenario@~0.1
53 verbose lock karma-ng-scenario@~0.1 C:\Users\reevesh\AppData\Roaming\npm-cache\8186ecb3-karma-ng-scenario-0-1.lock
54 silly addNameRange { name: 'phantomjs',
54 silly addNameRange   range: '>=1.9.0-0 <1.10.0-0',
54 silly addNameRange   hasData: false }
55 silly addNameRange { name: 'karma', range: '>=0.10.0-0 <0.11.0-0', hasData: false }
56 verbose request where is /phantomjs
57 verbose request registry https://registry.npmjs.org/
58 verbose request id 9e8e5099a4c48a2e
59 verbose url raw /phantomjs
60 verbose url resolving [ 'https://registry.npmjs.org/', './phantomjs' ]
61 verbose url resolved https://registry.npmjs.org/phantomjs
62 verbose request where is https://registry.npmjs.org/phantomjs
63 info trying registry request attempt 1 at 13:53:55
64 http GET https://registry.npmjs.org/phantomjs
65 verbose request where is /karma
66 verbose request registry https://registry.npmjs.org/
67 verbose url raw /karma
68 verbose url resolving [ 'https://registry.npmjs.org/', './karma' ]
69 verbose url resolved https://registry.npmjs.org/karma
70 verbose request where is https://registry.npmjs.org/karma
71 info trying registry request attempt 1 at 13:53:55
72 http GET https://registry.npmjs.org/karma
73 silly addNameRange { name: 'karma-ng-scenario',
73 silly addNameRange   range: '>=0.1.0-0 <0.2.0-0',
73 silly addNameRange   hasData: false }
74 silly addNameRange { name: 'karma-jasmine',
74 silly addNameRange   range: '>=0.1.0-0 <0.2.0-0',
74 silly addNameRange   hasData: false }
75 silly addNameRange { name: 'karma-junit-reporter',
75 silly addNameRange   range: '>=0.1.0-0 <0.2.0-0',
75 silly addNameRange   hasData: false }
76 verbose request where is /karma-ng-scenario
77 verbose request registry https://registry.npmjs.org/
78 verbose url raw /karma-ng-scenario
79 verbose url resolving [ 'https://registry.npmjs.org/', './karma-ng-scenario' ]
80 verbose url resolved https://registry.npmjs.org/karma-ng-scenario
81 verbose request where is https://registry.npmjs.org/karma-ng-scenario
82 info trying registry request attempt 1 at 13:53:55
83 http GET https://registry.npmjs.org/karma-ng-scenario
84 verbose request where is /karma-jasmine
85 verbose request registry https://registry.npmjs.org/
86 verbose url raw /karma-jasmine
87 verbose url resolving [ 'https://registry.npmjs.org/', './karma-jasmine' ]
88 verbose url resolved https://registry.npmjs.org/karma-jasmine
89 verbose request where is https://registry.npmjs.org/karma-jasmine
90 info trying registry request attempt 1 at 13:53:55
91 http GET https://registry.npmjs.org/karma-jasmine
92 verbose request where is /karma-junit-reporter
93 verbose request registry https://registry.npmjs.org/
94 verbose url raw /karma-junit-reporter
95 verbose url resolving [ 'https://registry.npmjs.org/', './karma-junit-reporter' ]
96 verbose url resolved https://registry.npmjs.org/karma-junit-reporter
97 verbose request where is https://registry.npmjs.org/karma-junit-reporter
98 info trying registry request attempt 1 at 13:53:55
99 http GET https://registry.npmjs.org/karma-junit-reporter
100 info retry will retry, error on last attempt: Error: socket hang up
101 info retry will retry, error on last attempt: Error: socket hang up
102 info retry will retry, error on last attempt: Error: read ECONNRESET
103 info retry will retry, error on last attempt: Error: read ECONNRESET
104 info retry will retry, error on last attempt: Error: socket hang up
105 info trying registry request attempt 2 at 13:54:05
106 http GET https://registry.npmjs.org/karma
107 info trying registry request attempt 2 at 13:54:05
108 http GET https://registry.npmjs.org/phantomjs
109 info trying registry request attempt 2 at 13:54:05
110 http GET https://registry.npmjs.org/karma-junit-reporter
111 info trying registry request attempt 2 at 13:54:05
112 http GET https://registry.npmjs.org/karma-ng-scenario
113 info trying registry request attempt 2 at 13:54:05
114 http GET https://registry.npmjs.org/karma-jasmine
115 info retry will retry, error on last attempt: Error: socket hang up
116 info retry will retry, error on last attempt: Error: read ECONNRESET
117 info retry will retry, error on last attempt: Error: read ECONNRESET
118 info retry will retry, error on last attempt: Error: read ECONNRESET
119 info retry will retry, error on last attempt: Error: read ECONNRESET
120 info trying registry request attempt 3 at 13:55:05
121 http GET https://registry.npmjs.org/karma
122 info trying registry request attempt 3 at 13:55:05
123 http GET https://registry.npmjs.org/phantomjs
124 info trying registry request attempt 3 at 13:55:05
125 http GET https://registry.npmjs.org/karma-junit-reporter
126 info trying registry request attempt 3 at 13:55:05
127 http GET https://registry.npmjs.org/karma-ng-scenario
128 info trying registry request attempt 3 at 13:55:05
129 http GET https://registry.npmjs.org/karma-jasmine
130 silly lockFile 472de541-phantomjs-1-9 phantomjs@~1.9
131 silly lockFile 472de541-phantomjs-1-9 phantomjs@~1.9
132 silly lockFile dbcabe50-karma-junit-reporter-0-1 karma-junit-reporter@~0.1
133 silly lockFile dbcabe50-karma-junit-reporter-0-1 karma-junit-reporter@~0.1
134 silly lockFile 8186ecb3-karma-ng-scenario-0-1 karma-ng-scenario@~0.1
135 silly lockFile 8186ecb3-karma-ng-scenario-0-1 karma-ng-scenario@~0.1
136 silly lockFile 059b5650-karma-0-10 karma@~0.10
137 silly lockFile 059b5650-karma-0-10 karma@~0.10
138 silly lockFile 0a4b2533-karma-jasmine-0-1 karma-jasmine@~0.1
139 silly lockFile 0a4b2533-karma-jasmine-0-1 karma-jasmine@~0.1
140 error network socket hang up
140 error network This is most likely not a problem with npm itself
140 error network and is related to network connectivity.
140 error network In most cases you are behind a proxy or have bad network settings.
140 error network
140 error network If you are behind a proxy, please make sure that the
140 error network 'proxy' config is set properly.  See: 'npm help config'
141 error System Windows_NT 6.1.7601
142 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
143 error cwd C:\Users\reevesh\Downloads\AngularDemos\angular-seed-master
144 error node -v v0.10.32
145 error npm -v 1.4.28
146 error code ECONNRESET
147 verbose exit [ 1, true ]

What do I need to do to fix this?

**Comment by joeeames** [comment]
gonna close this issue. assume it's resolved
